export const columns = [
    {
      id: "ID",
      label: "ID",
      minWidth: "",
      align: "left",
    },
    {
      id: "Title",
      label: "Title",
      minWidth: 180,
      align: "left",
    },
    {
      id: "Dpt",
      label: "Dpt.",
      minWidth: 70,
      align: "left",
    },
    {
      id: "Return",
      label: "Return",
      minWidth: 70,
      align: "left",
    },
    {
      id: "Status",
      label: "Status",
      minWidth: "",
      align: "left",
    },
  ];


  export const rowData = [
    // {
    //   id: 1,
    //   label: 1,
    //   title: "My First Booking Request",
    //   dpt: new Date().toLocaleDateString(),
    //   return: new Date().toLocaleDateString(),
    //   status: "Pending",
    // },
    // {
    //   id: 2,
    //   label: 2,
    //   title: "My Second Booking Request",
    //   dpt: new Date().toLocaleDateString(),
    //   return: new Date().toLocaleDateString(),
    //   status: "Booked",
    // },
    // {
    //   id: 3,
    //   label: 3,
    //   title: "My Third Booking Request",
    //   dpt: new Date().toLocaleDateString(),
    //   return: new Date().toLocaleDateString(),
    //   status: "Pending",
    // },
    // {
    //     id: 4,
    //     label: 4,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 5,
    //     label: 5,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 6,
    //     label: 6,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 7,
    //     label: 7,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 8,
    //     label: 8,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 9,
    //     label: 9,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 10,
    //     label: 10,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
    //   {
    //     id: 11,
    //     label: 11,
    //     title: "My Third Booking Request",
    //     dpt: new Date().toLocaleDateString(),
    //     return: new Date().toLocaleDateString(),
    //     status: "Pending",
    //   },
  ];